DROP TABLE IF EXISTS person_hall  CASCADE;
DROP TABLE IF EXISTS teaching     CASCADE;
DROP TABLE IF EXISTS mentorship   CASCADE;
DROP TABLE IF EXISTS door         CASCADE;
DROP TABLE IF EXISTS hall         CASCADE;
DROP TABLE IF EXISTS campus       CASCADE;
DROP TABLE IF EXISTS subject      CASCADE;
DROP TABLE IF EXISTS person       CASCADE;
