#+LANG: ru
#+TITLE: Семинар 6: Аллокация памяти, архитектура

* Что такое куча

В рамках этого семинара мы познакомимся с тем, как может быть устроена куча.

С данными связана такая характеристика как /время жизни/.
Это тот промежуток выполнения программы, когда обращаться к этим данным корректно и не ведёт к неопределённому поведению.

Данные в C могут быть выделены следующими способами:

- Автоматически: локальные переменные функций создаются в момент их запуска и живут до их завершения.
  Правильно сказать: гарантированное время жизни переменных от запуска функции до её завершения.

  Зная, что компиляторы оптимизируют локальные переменные, мы больше не будем говорить, что они выделяются в стеке.

- Глобальные переменные и локальные переменные функций, если локальные переменные помечены =static=.

  И те, и другие создаются в глобальной области данных.

Других гарантированно возможных способов выделить память в "голом" C нет.


Чтобы выделить память в стеке или в глобальной области данных необходимо знать, сколько именно памяти понадобится, уже в момент компиляции.
Однако иногда мы не знаем этого заранее; например, когда принимаем по сети размер строки и саму строку; её нужно где-то выделить, а сколько под это выделять байт --- неясно.

В таком случае приходится использовать =аллокаторы= --- специальные программы, которые умеют резервировать области памяти и управляют тем, где будут находиться блоки памяти, которые программист запрашивает.

Функции =malloc=, =calloc=, =realloc=, =free= --- это интерфейс к аллокатору из стандартной библиотеки C.
С помощью вызова =malloc= можно выделить память, время жизни которой будет неопределённо долгим. Она может существовать до завершения работы программы, как глобальные переменные, или быть возвращена для переиспользования с помощью функции =free=.


Некоторые советы по работе с памятью:

- Если вам нужно выделить память, подумайте, нельзя ли её выделить в стеке. Это всегда проще, чем в  куче.
- Не стесняйтесь передавать не очень большие структуры по значению.


* Аллокатор блоков

Самый простой аллокатор возвращает блоки фиксированного размера.
Их можно заполнять не полностью, остаток будет теряться.
Помимо блоков нужно хранить карту их занятости; здесь она хранится в виде массива =bool='ов, но для компактности можно было бы упаковывать булевы значения по восемь в каждый байт.

#+begin_src c

#define HEAP_BLOCKS 80
#define BLOCK_CAPACITY 1024

struct heap {
  struct block {
    char contents[BLOCK_CAPACITY];
  } blocks[HEAP_BLOCKS];
  bool is_occupied[HEAP_BLOCKS];
} global_heap = {0};
#+end_src


*Задание 1* Изучите файл [[./heap-0.c][heap-0.c]]  и реализуйте в нём недостающие функции для резервирования блока и для возвращения блока в пул доступных. Почему =block_id= содержит ссылку на =struct heap=?

** Аллокатор множества блоков


В предыдущем аллокаторе есть несколько существенных недостатков:

- блоки и заголовки перемежаются, и размер блоков фиксирован, поэтому нельзя занять несколько блоков подряд.
- размер блока фиксирован, и потому мы можем нести накланые расходы по памяти.


*Задание 2* Модифицируйте аллокатор так, чтобы он умел выделять несколько блоков подряд.
См. файл [[./heap-1.c][heap-1.c]]. У блоков теперь будет статус с большей гранулярностью, нежели "занят --- не занят". 
Придумайте тесты для вашего кода для проверки всех особых случаев.

#+begin_src c
enum block_status { BLK_FREE = 0, BLK_ONE, BLK_FIRST, BLK_CONT, BLK_LAST };
#+end_src 

Блоки будут связываться в одну из следующих конфигураций:

#+begin_src c
BLK_FREE //  свободный блок
BLK_ONE //  единичный занятый блок.
// после него или свободный или занятый другими данными.

BLK_FIRST, BLK_CONT, BLK_CONT, BLK_LAST
// последовательность блоков с  началом, серединкой и концом.

BLK_FIRST, BLK_LAST  // то же, но без серединки.

#+end_src 

Выделение памяти должно привести к выделению адекватного количества блоков; освобождение памяти должно привести к освобождению блоков начиная с указанного, если этот блок -- начало.


** Чего не хватает для эффективности?

Чтобы аллокатор стал более эффективным, можно отказаться от фиксированного размера блока, снабдив каждый из них заголовком и организовав в связный список.
Затем из единой непрерывной кучи можно сделать несколько фрагментов и добавить довыделение памяти (а именно страниц от операционной системы) в случае, когда куча закончилась.
Это и будет темой четвертой лабораторной работы.

* Задание 3

В качестве последнего задания на 2 балла вы можете выбрать одно из двух заданий.

** Задание 3, первый вариант

Первый вариант задания - это реализация несложной структуры данных как абстрагированного модуля с непрозрачным типом. Ему посвящена эта заметка.
 
*Изначальный код*

  У вас есть код внутри одной функции =main=, который реализует расширяемый массив (вектор).
  Изучите его.

#+begin_src c
/* bad.c */

#include <inttypes.h>
#include <malloc.h>
#include <stdio.h>

int main() {
  int64_t *array = malloc(sizeof(int64_t) * 5);
  // вместимость -- сколько памяти выделено
  size_t capacity = 5;
  // количество -- сколько памяти по факту используется из выделенной.
  size_t count = 0;
  // заполните массив квадратами чисел от 0 до 100
  // если не хватает места, расширяем в два раза
  for (size_t i = 0; i <= 100; i++) {
    if (count == capacity) {
      array = realloc(array, sizeof(int64_t) * capacity * 2);
      capacity = capacity * 2;
    }
    array[count++] = i * i;
  }

  for (size_t i = 0; i < 100; i++) {
    printf("%" PRId64 " ", array[i]);
  }
  return 0;
}
#+end_src 
   
  Расширяемый массив в отличие от обычного имеет нефиксированный размер, в конец такого массива можно добавлять элементы.
  Как это работает:
  - Мы выделяем память с запасом.
  - Мы храним два дополнительных числа: количество выделенных слотов под элементы и количество заполненных слотов в массиве.
  - Пока у нас хватает выделенных слотов, мы просто дописываем элементы в массив, увеличивая количество занятых слотов.
  - Если слотов перестало хватать, то увеличиваем количество слотов в 2 раза (или линейно на некоторый фиксированный размер). 
    Для этого используем =realloc= чтобы скопировать выделенную память в расширенный участок.

  *Вопрос* Прочитайте раздел =man malloc= про функцию =realloc=.
   
*Задача*

  Ваша задача --- выделить из этого кода как минимум модуль с реализацией вектора, снабжённый заголовочным файлом.

  - Вектор должен быть реализован как [[https://stepik.org/lesson/408352/step/6][непрозрачная структура данных]].
  - Доступ к его элементам должен быть контролируем и осуществляться через getter и setter.
  - Постарайтесь максимально переиспользовать код и ничего не дублировать.
  - Вывод вектора реализуйте как отдельную функцию, которая принимает =FILE*=, в который нужно вывести его содержимое.
    Эту функцию можно также разбить на функцию =foreach= и принтер одного элемента.
  - Стремитесь сделать настолько маленькие функции, насколько возможно.

  Ваша реализацяия как минимум должна позволять:
  - Получить доступ к любому элементу.
  - Получить информацию о текущей длинне массива и количестве выделенной памяти.
  - Добавить элемент в конец массива.
  - Добавить другой массив в конец массива (скопировать данные).
  - Изменить размер массива на заданный (при необхоимости выделить память).
  - Изменить размер массива на меньший с освобождением неиспользуемой памяти.
  - Освободить память.
  - Вывести массив в указанный поток вывода.

  В результате должна получиться программа из нескольких файлов, которая делает то же самое, но в которой =main= содержит только заполнение вектора числами и вызов функции, печатающей его в =stdout=.
   
  Прочитайте заметку [[[https://gitlab.se.ifmo.ru/c-language/main/-/wikis/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0-%D1%81%D1%82%D0%B8%D0%BB%D1%8F-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC-%D0%BD%D0%B0-C][Правила хорошего стиля]]] --- ваш код должен им соответствовать.
  


** Задание 3, второй вариант

Второй вариант задания - это развитие принтера, который вы увидели на прошлом семинаре.
Добавьте туда:

- вычислитель, который умеет вычислять формулы. Сделайте его расширяемым, так же, как сделан принтер. Подсказка: в отличие от принтера, который не имеет состояния, для вычисления потребуется накапливать состояние, поэтому функции будут иметь больше аргументов, нежели принтеры для узлов.
- парсер, который сможет распознавать верные формулы из сложения, умножения, деления и вычитания. Не забудьте про скобки!
- принтер, который будет выводить выражение используя постфиксную запись (обратная польская запись, без использования скобок).

В качестве стартовой точки для выполнения этого задания можете использовать расширенный вариант принтера ([[./printer]]), 
в который уже включен базовый токенайзер ([[./printer/tokenizer.h][tokenizer.h]], [[./printer/tokenizer.c][tokenizer.c]]), 
а также кольцо абстракнтых типов ([[./printer/ring.h][printer/ring.h]]), которое можно использовать как стек или очередь.

*** Алгоритм построения AST дерева для арифметических выражений

*Описание токенов*

Токены делятся на три основные категории:
1. *Литералы* — целые числа, тип #TOK_LIT#.
2. *Операторы* — математические операции: `+` (=TOK_PLUS=), `-` (=TOK_MINUS=), `*` (=TOK_MUL=), `/` (=TOK_DIV=), и унарное изменение знака `-` (=TOK_NEG=).
3. *Скобки* — открывающая и закрывающая скобки `(` (=TOK_OPEN=) и `)` (=TOK_CLOSE=).

*** Структура узла AST дерева

Для представления узлов дерева будем использовать структуру с прошлого семинара:

#+begin_src c
struct AST {
  enum AST_type { AST_BINOP, AST_UNOP, AST_LIT } type;
  union {
    struct binop {
      enum binop_type { BIN_PLUS, BIN_MINUS, BIN_MUL, BIN_DIV } type;
      struct AST *left, *right;
    } as_binop;
    struct unop {
      enum unop_type { UN_NEG } type;
      struct AST *operand;
    } as_unop;
    struct literal {
      int64_t value;
    } as_literal;
  };
};
#+end_src

*Операнды и операторы*

Для хранения временных данных будем использовать два стека:
- *Стек операндов* для хранения узлов дерева.
- *Стек операторов* для хранения операторов и скобок.

В качестве реализации стека будем использовать структуру данных кольцо, что позволит исаользовать одну и ту же структуру данных как для очереди токенов, так и для стеков. Структура данных реализована с использованием макросов, что позволит нам использовать её для любого типа данных (см. [[./printer/ring.h][printer/ring.h]]).

#+begin_src c
DECLARE_RING(ast, struct AST)
DEFINE_RING(ast, struct AST)
DEFINE_RING_PRINT(ast, ast_print)
DECLARE_RING(token, struct token)
DEFINE_RING(token, struct token)
DEFINE_RING_PRINT(token, token_print)

struct ring_ast *ast_stack = NULL;
struct ring_token *token_stack = NULL;
#+end_src

*Приоритеты операций*

Для управления приоритетами операций создадим функцию `priority()`, которая возвращает значение приоритета для каждого токена оператора:

#+begin_src c
int priority(struct token token)
{
  switch (token.type)
  {
    case TOK_OPEN:
    case TOK_CLOSE:
      return 0;
    case TOK_PLUS:
    case TOK_MINUS:
      return 1;
    case TOK_MUL:
    case TOK_DIV:
      return 2;
    case TOK_NEG:
      return 3;
    default:
      printf("Unexpected token for priority.\n");
      return -1;
  }
}
#+end_src

*** Основной цикл обработки токенов

Полученная на вход очередь токенов обрабатывается следующим образом:
1. Если следующий токен — это литерал, то создаём узел AST и помещаем его в стек операндов.
2. Если следующий токен — оператор, проверяем приоритет операторов в стеке.
3. Если следующий токен — открывающая скобка, помещаем её в стек операторов.
4. Если следующий токен — закрывающая скобка, выполняем построение дерева для всех элементов в стеке операторов до открывающейся скобки.

#+begin_src c
struct ring_token *tokens = NULL;
if ((tokens = tokenize(str)) == NULL)
  RETURN_ERROR(NULL, "Tokenization error.\n");
struct token prev = (struct token){TOK_PLUS, 0};
while (tokens != NULL)
{
  struct token token = ring_token_poptop(&tokens);
  struct AST ast = TOKENS_AST[token.type];

  // обработать следующий токен
  // ...
}
#+end_src

*Обработка литералов*

Для литерала просто создаём узел AST и помещаем его в стек операндов.

#+begin_src c
if (token.type == TOK_LIT)
{
  ast.as_literal.value = token.value;
  ring_ast_pushback(&ast_stack, ast);
  prev = token;
  continue;
}
#+end_src


*Обработка операторов*

Когда мы встречаем оператор, необходимо сравнить его приоритет с операторами в стеке. Если оператор в стеке имеет больший или равный приоритет, необходимо выполнить соответствующие операции, создавая новые узлы дерева.

#+begin_src c
if (token_stack == NULL || priority(ring_token_last(token_stack)) < priority(token))
{
    ring_token_push(&token_stack, token);
    prev = token;
    continue;
}

if (token_stack == NULL || priority(ring_token_last(token_stack)) == priority(token))
{
  merge_node(&ast_stack, &token_stack);
  ring_token_push(&token_stack, token);
  prev = token;
  continue;
}

while (token_stack != NULL && priority(ring_token_last(token_stack)) >= priority(token))
{
  merge_node(&ast_stack, &token_stack)
}

ring_token_push(&token_stack, token);
prev = token;
#+end_src

Функция #merge_node# выполняет одну операцию со стека. То есть она снимает со стека операторов один оператор, снимает со стека операндов требуемое количество операндов, создает новый узел AST дерева и добавляет его в дерево операция.

*Обработка скобок*

- *Открывающая скобка* просто помещается в стек операторов.
- *Закрывающая скобка* вызывает выполнение всех операций из стека операций до первой открывающей скобки.

#+begin_src c
if (token.type == TOK_OPEN)
{
  ring_token_push(&token_stack, token);
  prev = token;
  continue;
}

if (token.type == TOK_CLOSE)
{
  do
  {
    merge_node(&ast_stack, &token_stack);
  } while (token_stack != NULL && ring_token_last(token_stack).type != TOK_OPEN);
  ring_token_pop(&token_stack);
  prev = token;
  continue;
}
#+end_src

*Завершение вычислений*

После того как все токены обработаны, необходимо выполнить все оставшиеся операции, находящиеся в стеке операторов

#+begin_src c
while (token_stack != NULL)
  merge_node(&ast_stack, &token_stack);
#+end_src
